openapi: 3.0.0
info:
  version: 1.0.0
  title: DuplicaAPI
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: 'List the users of the system'
      operationId: listUsers
      tags:
        - user
      responses:
        '200':
          $ref: '#/components/responses/ListOfUsers'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/UnexpectedError'
          
components:
  responses:
    ListOfUsers:
      description: List of all users ordered by name
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
    Unauthorized:
      description: Unauthorized Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not Found Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    UnprocessableEntity:
      description: Unprocessable Entity Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExpressValidatorError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    UnexpectedError:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    User:
      type: object
      required:
        - username
        - password
        - role
      properties:
        username:
          type: string
        password:
          type: string
        role:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    ExpressValidatorError:
      type: object
      required:
        - msg
        - param
        - value
        - location
      properties:
        msg:
          type: string
        param:
          type: string
        value:
          type: string
        location:
          type: string