openapi: 3.0.0
info:
  version: 1.0.0
  title: DuplicaAPI
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: 'List the users of the system'
      operationId: listUsers
      tags:
        - user
      responses:
        '200':
          $ref: '#/components/responses/ListOfUsers'
        default:
          $ref: '#/components/responses/UnexpectedError'
          
components:
  responses:
    ListOfUsers:
      description: List of all users ordered by name
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
    UnexpectedError:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    User:
      type: object
      required:
        - username
        - password
        - role
      properties:
        username:
          type: string
        password:
          type: string
        role:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string